### ISSUE TITLE
Wikipedia page

### ISSUE THREAD

**Issue by Saichethan** [codeuino/website-www.codeuino.org#23] opened 2018-06-22 03:34 UTC
It's better if we have a Wikipedia page for Codeuino this helps in indexing site and forming rich cards so, interested people please start working on it.

**Comment by jaskirat2000** [comment] 2018-06-22 05:29
Sounds good, i will make that so that others can also contribute there

**Comment by devshiva619** [comment] 2018-08-26 09:41
@jaskirat2000 can we close this one?

**Comment by jaskirat2000** [comment] 2019-01-08 17:30
@saichethan can you help us writing in this ?

**Comment by Saichethan** [comment] 2019-01-08 17:59
@jaskirat2000 I tried many times but it went into speedy deletion category and my draft was reverted back by maintainers

**Comment by jaskirat2000** [comment] 2019-01-08 18:00
Can you let me know the cause? Do you have a draft for it ?

**Closed** 2019-02-27 12:19 UTC
Labels: enhancement, good first issue
